[package]
name = "drodt-tmpl"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Daniel Drodt <daniel.drodt@tu-darmstadt.de>"]
license = "MIT"
description = "My default template"

[template]
path = "template"
entrypoint = "main.typ"
