[conf]
default-lang = "en"

[lang.en]
range-conj = " to "
pair-conj = " and "
middle-conj = ", "
last-conj = " and "
middle-group-conj = ", "
last-group-conj = ", and "
equation-pl = "equations"
figure-pl = "figures"
table-pl = "tables"
page-pl = "pages"
part-pl = "parts"
chapter-pl = "chapters"
section-pl = "sections"
appendix-pl = "appendices"
enumi-pl = "items"
footnote-pl = "footnotes"
theorem-pl = "theorems"
lemma-pl = "lemmas"
corollary-pl = "corollaries"
proposition-pl = "propositions"
definition-pl = "definitions"
result-pl = "results"
example-pl = "examples"
remark-pl = "remarks"
note-pl = "notes"
algorithm-pl = "algorithms"
listings-pl = "listings"
line-pl = "lines"
Equation-pl = "Equations"
Figure-pl = "Figures"
Table-pl = "Tables"
Page-pl = "Pages"
Part-pl = "Parts"
Chapter-pl = "Chapters"
Section-pl = "Sections"
Appendix-pl = "Appendices"
Enumi-pl = "Items"
Footnote-pl = "Footnotes"
Theorem-pl = "Theorems"
Lemma-pl = "Lemmas"
Corollary-pl = "Corollaries"
Proposition-pl = "Propositions"
Definition-pl = "Definitions"
Result-pl = "Results"
Example-pl = "Examples"
Remark-pl = "Remarks"
Note-pl = "Notes"
Algorithm-pl = "Algorithms"
Listings-pl = "Listings"
Line-pl = "Lines"

[lang.de]
range-conj = " bis "
pair-conj = " und "
middle-conj = ", "
last-conj = " und "
middle-group-conj = ", "
last-group-conj = " und "
Gleichung-pl = "Gleichungen"
Abbildung-pl = "Abbildungen"
Tabelle-pl = "Tabellen"
Page-pl = "Seiten"
Teil-pl = "Teile"
Kapitel-pl = "Kapitel"
Abschnitt-pl = "Abschnitte"
Anhang-pl = "Anhänge"
Punkt-pl = "Punkte"
"Fußnote-pl" = "Fußnoten"
Theorem-pl = "Theorem"
Lemma-pl = "Lemmata"
Korollar-pl = "Korollare"
Satz-pl = "Sätze"
Definition-pl = "Definitionen"
Ergebnis-pl = "Ergebnisse"
Beispiel-pl = "Beispiele"
Bemerkung-pl = "Bemerkungen"
Anmerkung-pl = "Anmerkungen"
Algorithmus-pl = "Algorithmen"
Listing-pl = "Listings"
Zeile-pl = "Zeilen"
